### ISSUE TITLE
Crash on startup after updating to 1.2.0

### ISSUE THREAD

**Issue by BeardStroker** [quat1024/incorporeal#28]
Forge 14.23.5.2838
Incorporeal 1.2.0
Mob grinding utilities 0.3.13

Hi there, Just updating some mods when this crash at startup happened. I saw a similar post in the closed section but I am not sure if it is related so I made a new post. If I can provide any more information just let me know :) Downgrading to previous version for now.

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from mob_grinding_utils (mob_grinding_utils)
Caused by: java.lang.NoClassDefFoundError: com/elytradev/infraredstone/InfraRedstone
    at quaternary.incorporeal.feature.compat.infraredstone.InRedAttachCapabilitiesEventHandler.<clinit>(InRedAttachCapabilitiesEventHandler.java:31)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3198_InRedAttachCapabilitiesEventHandler_tileCaps_AttachCapabilitiesEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:691)
    at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:655)
    at net.minecraft.tileentity.TileEntity.<init>(TileEntity.java:478)
    at mob_grinding_utils.tile.TileEntityInventoryHelper.<init>(TileEntityInventoryHelper.java:18)
    at mob_grinding_utils.tile.TileEntitySaw.<init>(TileEntitySaw.java:38)
    at mob_grinding_utils.MobGrindingUtils.preInit(MobGrindingUtils.java:109)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.elytradev.infraredstone.InfraRedstone
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 50 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 52 more

**Comment by quat1024** [comment]
Oh no, I forgot to make the compatubility modules not load if their required mods aren't loaded !!

Has incorporeal.cfg been generated? Disable the compatibility in the settings

**Comment by angelnc1989** [comment]
https://paste.dimdev.org/avododokaf.mccrash

Got a similar crash. The config has been generated and disabling InfraRedstone compatibility fixes it.

**Comment by Sunconure11** [comment]
https://paste.dimdev.org/yihapeyefu.mccrash

Issue may be connected to Rustic.

**Comment by Zygus42** [comment]
Not connected to Rustic, as I'm getting the same issue with Quark.
[crash-2019-08-15_07.21.35-client.txt](https://github.com/quat1024/incorporeal/files/3503719/crash-2019-08-15_07.21.35-client.txt)

**Comment by quat1024** [comment]
Im gonna submit the fix in a little bit, having some trouble compiling the mod for some reason

**Comment by quat1024** [comment]
It's posted, will be [here](https://www.curseforge.com/minecraft/mc-mods/incorporeal/files/2762812) in a little bit, version is 1.2.1

**Comment by Zygus42** [comment]
v1.2.1:
[crash-2019-08-16_13.58.45-client.txt](https://github.com/quat1024/incorporeal/files/3508239/crash-2019-08-16_13.58.45-client.txt)

**Comment by quat1024** [comment]
The fuck

**Comment by BeardStroker** [comment]
The update fixed it for me, thanks a bunch :)
